### ISSUE TITLE
Tumblr subdomains do not work with dpi bypass enabled.

### ISSUE THREAD

**Issue by kotenok2000** [dovecoteescapee/ByeDPIAndroid#7]
When I open https://meraki-sunset.tumblr.com/ I get an error. It works with dpi bypass disabled.

**Comment by kotenok2000** [comment]
https://static1.e621.net also doesn't work.

**Comment by vlad54rus** [comment]
Also not working:
fandom.com
kaspersky.ru

**Comment by dovecoteescapee** [comment]
This is expected behavior, DPI bypass methods may break some sites. Since [version 1.0.2](https://github.com/dovecoteescapee/ByeDPIAndroid/releases/tag/1.0.2) you can use arbitrary arguments to ByDPI. Try `--auto=torst --timeout 3 -disorder 3` (or shortly `-A t -T 3 -d 3`). With these settings disordering will only be applied if the site has not loaded within 3 seconds.
